package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets AccountService_v1_13_0_AuthenticationTypes
 */
public enum AccountService_AuthenticationTypes   {
  
  TOKEN("Token"),
  
  KERBEROSKEYTAB("KerberosKeytab"),
  
  USERNAMEANDPASSWORD("UsernameAndPassword"),
  
  OEM("OEM");

  private String value;

  AccountService_AuthenticationTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AccountService_AuthenticationTypes fromValue(String value) {
    for (AccountService_AuthenticationTypes b : AccountService_AuthenticationTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

