package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The enumerations of BootOrderTypes specify the choice of boot order property to use when controller the persistent boot order for this computer system.
 */
public enum ComputerSystem_BootOrderTypes   {
  
  BOOTORDER("BootOrder"),
  
  ALIASBOOTORDER("AliasBootOrder");

  private String value;

  ComputerSystem_BootOrderTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ComputerSystem_BootOrderTypes fromValue(String value) {
    for (ComputerSystem_BootOrderTypes b : ComputerSystem_BootOrderTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

