package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets ComputerSystem_v1_20_1_BootProgressTypes
 */
public enum ComputerSystem_BootProgressTypes   {
  
  NONE("None"),
  
  PRIMARYPROCESSORINITIALIZATIONSTARTED("PrimaryProcessorInitializationStarted"),
  
  BUSINITIALIZATIONSTARTED("BusInitializationStarted"),
  
  MEMORYINITIALIZATIONSTARTED("MemoryInitializationStarted"),
  
  SECONDARYPROCESSORINITIALIZATIONSTARTED("SecondaryProcessorInitializationStarted"),
  
  PCIRESOURCECONFIGSTARTED("PCIResourceConfigStarted"),
  
  SYSTEMHARDWAREINITIALIZATIONCOMPLETE("SystemHardwareInitializationComplete"),
  
  SETUPENTERED("SetupEntered"),
  
  OSBOOTSTARTED("OSBootStarted"),
  
  OSRUNNING("OSRunning"),
  
  OEM("OEM");

  private String value;

  ComputerSystem_BootProgressTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ComputerSystem_BootProgressTypes fromValue(String value) {
    for (ComputerSystem_BootProgressTypes b : ComputerSystem_BootProgressTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

