package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets ComputerSystem_v1_20_1_GraphicalConnectTypesSupported
 */
public enum ComputerSystem_GraphicalConnectTypesSupported   {
  
  KVMIP("KVMIP"),
  
  OEM("OEM");

  private String value;

  ComputerSystem_GraphicalConnectTypesSupported(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ComputerSystem_GraphicalConnectTypesSupported fromValue(String value) {
    for (ComputerSystem_GraphicalConnectTypesSupported b : ComputerSystem_GraphicalConnectTypesSupported.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

