package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The enumerations of PowerRestorePolicyTypes specify the choice of power state for the system when power is applied.
 */
public enum ComputerSystem_PowerRestorePolicyTypes   {
  
  ALWAYSON("AlwaysOn"),
  
  ALWAYSOFF("AlwaysOff"),
  
  LASTSTATE("LastState");

  private String value;

  ComputerSystem_PowerRestorePolicyTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ComputerSystem_PowerRestorePolicyTypes fromValue(String value) {
    for (ComputerSystem_PowerRestorePolicyTypes b : ComputerSystem_PowerRestorePolicyTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

