package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets ExternalAccountProvider_v1_6_0_AccountProviderTypes
 */
public enum ExternalAccountProvider_AccountProviderTypes   {
  
  REDFISHSERVICE("RedfishService"),
  
  ACTIVEDIRECTORYSERVICE("ActiveDirectoryService"),
  
  LDAPSERVICE("LDAPService"),
  
  OEM("OEM"),
  
  TACACSPLUS("TACACSplus"),
  
  OAUTH2("OAuth2");

  private String value;

  ExternalAccountProvider_AccountProviderTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ExternalAccountProvider_AccountProviderTypes fromValue(String value) {
    for (ExternalAccountProvider_AccountProviderTypes b : ExternalAccountProvider_AccountProviderTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

