package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets LogEntry_v1_15_0_OriginatorTypes
 */
public enum LogEntry_OriginatorTypes   {
  
  CLIENT("Client"),
  
  INTERNAL("Internal"),
  
  SUPPORTINGSERVICE("SupportingService");

  private String value;

  LogEntry_OriginatorTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static LogEntry_OriginatorTypes fromValue(String value) {
    for (LogEntry_OriginatorTypes b : LogEntry_OriginatorTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

