package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets LogService_v1_4_0_LogDiagnosticDataTypes
 */
public enum LogService_LogDiagnosticDataTypes   {
  
  MANAGER("Manager"),
  
  PREOS("PreOS"),
  
  OS("OS"),
  
  OEM("OEM");

  private String value;

  LogService_LogDiagnosticDataTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static LogService_LogDiagnosticDataTypes fromValue(String value) {
    for (LogService_LogDiagnosticDataTypes b : LogService_LogDiagnosticDataTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

