package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets LogService_v1_4_0_LogEntryTypes
 */
public enum LogService_LogEntryTypes   {
  
  EVENT("Event"),
  
  SEL("SEL"),
  
  MULTIPLE("Multiple"),
  
  OEM("OEM");

  private String value;

  LogService_LogEntryTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static LogService_LogEntryTypes fromValue(String value) {
    for (LogService_LogEntryTypes b : LogService_LogEntryTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

