package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets ManagerAccount_AccountTypes
 */
public enum ManagerAccountAccountTypes {
  
  REDFISH("Redfish"),
  
  SNMP("SNMP"),
  
  OEM("OEM"),
  
  HOSTCONSOLE("HostConsole"),
  
  MANAGERCONSOLE("ManagerConsole"),
  
  IPMI("IPMI"),
  
  KVMIP("KVMIP"),
  
  VIRTUALMEDIA("VirtualMedia"),
  
  WEBUI("WebUI");

  private String value;

  ManagerAccountAccountTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ManagerAccountAccountTypes fromValue(String value) {
    for (ManagerAccountAccountTypes b : ManagerAccountAccountTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

