package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets Manager_v1_18_0_GraphicalConnectTypesSupported
 */
public enum Manager_GraphicalConnectTypesSupported   {
  
  KVMIP("KVMIP"),
  
  OEM("Oem");

  private String value;

  Manager_GraphicalConnectTypesSupported(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Manager_GraphicalConnectTypesSupported fromValue(String value) {
    for (Manager_GraphicalConnectTypesSupported b : Manager_GraphicalConnectTypesSupported.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

