package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets Manager_v1_18_0_CommandConnectTypesSupported
 */
public enum Manager_CommandConnectTypesSupported   {
  
  SSH("SSH"),
  
  TELNET("Telnet"),
  
  IPMI("IPMI"),
  
  OEM("Oem");

  private String value;

  Manager_CommandConnectTypesSupported(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Manager_CommandConnectTypesSupported fromValue(String value) {
    for (Manager_CommandConnectTypesSupported b : Manager_CommandConnectTypesSupported.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

