package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets PCIeSlots_v1_5_0_SlotTypes
 */
public enum PCIeSlots_SlotTypes   {
  
  FULLLENGTH("FullLength"),
  
  HALFLENGTH("HalfLength"),
  
  LOWPROFILE("LowProfile"),
  
  MINI("Mini"),
  
  M2("M2"),
  
  OEM("OEM"),
  
  OCP3SMALL("OCP3Small"),
  
  OCP3LARGE("OCP3Large"),
  
  U2("U2");

  private String value;

  PCIeSlots_SlotTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PCIeSlots_SlotTypes fromValue(String value) {
    for (PCIeSlots_SlotTypes b : PCIeSlots_SlotTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

