package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets PCIeDevice_PCIeTypes
 */
public enum PCIeDevicePCIeTypes {
  
  GEN1("Gen1"),
  
  GEN2("Gen2"),
  
  GEN3("Gen3"),
  
  GEN4("Gen4"),
  
  GEN5("Gen5");

  private String value;

  PCIeDevicePCIeTypes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PCIeDevicePCIeTypes fromValue(String value) {
    for (PCIeDevicePCIeTypes b : PCIeDevicePCIeTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

