package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets Resource_State
 */
public enum ResourceState {
  
  ENABLED("Enabled"),
  
  DISABLED("Disabled"),
  
  STANDBYOFFLINE("StandbyOffline"),
  
  STANDBYSPARE("StandbySpare"),
  
  INTEST("InTest"),
  
  STARTING("Starting"),
  
  ABSENT("Absent"),
  
  UNAVAILABLEOFFLINE("UnavailableOffline"),
  
  DEFERRING("Deferring"),
  
  QUIESCED("Quiesced"),
  
  UPDATING("Updating"),
  
  QUALIFIED("Qualified");

  private String value;

  ResourceState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ResourceState fromValue(String value) {
    for (ResourceState b : ResourceState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

