package org.picmg.redfish_server_template.RFmodels.Autogenerated;

import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets Task_v1_7_1_TaskState
 */
public enum Task_TaskState   {
  
  NEW("New"),
  
  STARTING("Starting"),
  
  RUNNING("Running"),
  
  SUSPENDED("Suspended"),
  
  INTERRUPTED("Interrupted"),
  
  PENDING("Pending"),
  
  STOPPING("Stopping"),
  
  COMPLETED("Completed"),
  
  KILLED("Killed"),
  
  EXCEPTION("Exception"),
  
  SERVICE("Service"),
  
  CANCELLING("Cancelling"),
  
  CANCELLED("Cancelled");

  private String value;

  Task_TaskState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Task_TaskState fromValue(String value) {
    for (Task_TaskState b : Task_TaskState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

