server:
  port: 8443
  http_port: 8080
  ssl:
      key-store: "${user.home}/keys/rfserver.p12"
      key-store-password: "store_password"
      key-store-type: "pkcs12"
      key-alias: "redfish_server"
      key-password: "store_password"