//******************************************************************************************************
// SessionController.java
//
// Controller for Session service.
//
//Copyright (C) 2022, PICMG.
//
//        This program is free software: you can redistribute it and/or modify
//        it under the terms of the GNU General Public License as published by
//        the Free Software Foundation, either version 3 of the License, or
//        (at your option) any later version.
//
//        This program is distributed in the hope that it will be useful,
//        but WITHOUT ANY WARRANTY; without even the implied warranty of
//        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//        GNU General Public License for more details.
//
//        You should have received a copy of the GNU General Public License
//        along with this program.  If not, see <https://www.gnu.org/licenses/>.
//*******************************************************************************************************

package org.picmg.redfish_server_template.controllers;

import org.picmg.redfish_server_template.RFmodels.Autogenerated.RedfishError;
import org.picmg.redfish_server_template.RFmodels.custom.CachedSchema;
import org.picmg.redfish_server_template.RFmodels.custom.RedfishObject;
import org.picmg.redfish_server_template.services.AccountService;
import org.picmg.redfish_server_template.services.RedfishErrorResponseService;
import org.picmg.redfish_server_template.services.SessionTimeoutService;
import org.picmg.redfish_server_template.services.jwt.JWTService;
import org.picmg.redfish_server_template.services.SessionService;
import org.openapitools.jackson.nullable.JsonNullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.scheduling.config.FixedRateTask;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.web.bind.annotation.*;
import javax.servlet.http.HttpServletRequest;
import java.time.OffsetDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;


@RestController
@RequestMapping(value = "/redfish/v1/SessionService/Sessions")
public class SessionController extends RedfishObjectController {
    @Autowired
    SessionService sessionService;
    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    JWTService jwtService;

    @Autowired
    AccountService accountService;

    @Autowired
    SessionTimeoutService sessionTimeoutService;

    // there are no subordinates to delete, however, when the object is deleted, the timing information for it
    // needs to be removed form the map.
    protected void onDeleteRemoveSubordinates(RedfishObject obj, HttpServletRequest ignoredRequest) {
        // force a removal next time it is checked
        sessionTimeoutService.hintForRemoval(obj.get("UserName").toString());
    }

    // onPostCompleteMissingFields()
    //
    // This method is called during an HTTP post request after initial payload has been validated against the schema.
    // It can be assumed that the payload has all required fields for onCreate, but other required fields may be missing.
    // This method completes field data for any required fields and the updated redfish object is returned.
    //
    // The default behavior of this function is to complete the @odata.id, id, and Name fields.  @odata.type has
    // already been completed. Objects that extend this class should update any other required fields.
    //
    // parameters:
    //    RedfishObject obj -- the object to be posted
    //    HttpServletRequest request -- the post request that was received
    //    CachedSchema schema -- the related schema object for the posted data
    //
    // returns:
    //    RedfishObject with updated fields
    //
    protected RedfishObject onPostCompleteMissingFields(RedfishObject obj, HttpServletRequest request, CachedSchema schema) {
        // if the session already exists, use the existing one
        RedfishObject session = sessionService.getSessionByUserName(obj.getString("UserName"));
        if (session!=null) {
            // if it already exists, use the existing session - this will force the response to use the
            // existing session instead.
            return session;
        }
        session = super.onPostCompleteMissingFields(obj,request,schema);
        session.setName(obj.getString("UserName") + " Session");
        session.setDescription("User Session for " + obj.getString("UserName"));
        session.put("UserName",obj.getString("UserName"));
        // don't store the password field - although it is required on create, we don't need to store it.
        session.remove("Password");
        session.put("CreatedTime",OffsetDateTime.now().toString());

        return session;
    }

    // onPostUpdateResponse()
    //
    // This method updates the response to be sent based on any resource-specific requirements.
    //
    // The default behavior of this is to return null (no error). Objects that extend this class should
    // override this behavior to meet the needs of their specific object type.
    //
    // parameters:
    //    RedfishObject obj -- the object that was posted
    //    HttpServletRequest request -- the post request that was received
    //    CachedSchema schema -- the related schema object for the posted data
    //
    // returns:
    //    RedfishError if errors are found, otherwise null
    //
    @Override
    protected ResponseEntity<?> onPostUpdateResponse(RedfishObject obj, HttpServletRequest request, ResponseEntity<?> response) {
        // create/update an entry for this session in the activeSessionTiming map
        sessionTimeoutService.touch(obj.get("UserName").toString());

        // get the related account
        RedfishObject account = accountService.getAccountFromUserName(obj.getString("UserName"));
        if (account!=null) {
            String jwt = null;
            try {
                jwt = jwtService.generateToken(account, obj.getId());
                HttpHeaders respHeaders = new HttpHeaders();
                respHeaders.addAll(response.getHeaders());
                respHeaders.add("X-Auth-Token", jwt);
                return ResponseEntity.status(response.getStatusCode())
                        .headers(respHeaders).body(response.getBody());
            } catch (Exception ignored) {
            }
        }
        return response;
    }

}